### ISSUE TITLE
Using tr command with multibyte (UTF-8) characters

### ISSUE THREAD

**Issue by vitlav** [Vladimir-csp/xdg-terminal-exec#12]
xdg-terminal-exec uses
tr '\0' "$IFS"
where $IFS is an unicode symbol

It doesn't work for me. I got the result
```
$ echo 1 | tr '1' '│'
�
```
(instead of '│' symbol) both in latests Fedora and Ubuntu 20.04.

Also it can be strange if IFS will be a multibyte character.

**Comment by Vladimir-csp** [comment]
I'm getting the same result in dash and bash with running `echo 1 | tr '1' '│'` interactively (Debian testing), but xdg-terminal-exec works.
How does it break in your case?

Anyway, I can just iterate over punctuation ASCII characters. The downsides would include lots of tr invocations if arguments are rich in them, or a failure if argument happens to have all of them.
`for CHAR in ':' '#' '@' '%' '/' '^' '$' '=' '+' '*' '!' ';' 'END'`, with deliberate failure on "END". What do you think?
