### ISSUE TITLE
Add buildsystem

### ISSUE THREAD

**Issue by jbicha** [Vladimir-csp/xdg-terminal-exec#14]
It would be helpful to distros if xdg-terminal-exec included a build system.

This could be done with meson and it could include meson's support for running build tests.

**Comment by mcepl** [comment]
Why? There is nothing to build …

**Comment by Vladimir-csp** [comment]
For a single script there is nothing to build. And, to my horror, it is already packaged in at least 3 distros, so everything seems to be fine without a build system.
