### ISSUE TITLE
Exec fails if zsh is used as sh

### ISSUE THREAD

**Issue by eumpf0** [Vladimir-csp/xdg-terminal-exec#15]
If `/bin/sh` is symlinked to `zsh` instead of `bash`, the script fails on the final exec statement.
Seems to be a problem with zsh messing up the IFS character.

Relevant part of the DEBUG output:

> /usr/bin/xdg-terminal-exec:404: command not found: alacritty\M-b-e\M-bnvim

`IFS` was `'│'` (i.e. first in the list). I also tried the second IFS from the list, same error message still.

**possible upstream solution:**
- change shebang from `#!/bin/sh` to `#!/bin/bash` to force execution via bash.
_Caveat:_ forces execution via bash even though different shells might work flawlessly

**user end solution:**
- relink `sh` to `bash`

(This situation is probably the default for most users anyway, in my case however I had recently re-installed the OS on my laptop and automated the bootstrapping, including installing zsh early during OS install and did not even notice that zsh instead of bash had become the link target of `sh`, the latter was the case when I installed zsh later on (separate from OS setup) on another PC.)

**other fix that does not work:**
- in script check if executing shell is `zsh`, if so use zsh's builtin command `emulate sh` (should restrict `zsh` to posix features only), still getting same error

**suggestion:** If my proposed upstream solution is not an option because of the caveat (or there is no quick fix for zsh) I would alert zsh users to this problem in the README. Might save people some time trying to find the problem ;)
In case you'd like that  I'll gladly open a PR adding this and a test to check for incompatible `sh` configuration.

**Comment by Vladimir-csp** [comment]
I've switched delimiter candidates to ASCII chars in 8c3f03d for #12, does it work in zfs now?

**Comment by Vladimir-csp** [comment]
Multibyte chars no longer used
