### ISSUE TITLE
Sandbox compatibility

### ISSUE THREAD

**Issue by orowith2os** [Vladimir-csp/xdg-terminal-exec#16]
Hi, I was looking into this and noted that it might not work well if, say, a Flatpak were to open this (like for log viewing). I was wondering if something could be done for this. 

The basic idea I have is that, if a Flatpak used this utility, it would open the terminal on the host (no flatpak-spawn) and runs the commands given inside of the flatpak env, so it's not a sandbox escape.

**Comment by Vladimir-csp** [comment]
Not sure how to approach this, since I have not yet interacted with flatpak. Could you provide more info? What would run `xdg-terminal-exec` and what info would be available to pass to `flatpak-spawn (?)` when prepending it to command(?) ?

**Comment by orowith2os** [comment]
If it were to become an actual XDG spec, xdg-terminal-exec would implement a portal, org.freedesktop.portal.TerminalExec.

On the host, xdg-terminal-exec reads this dbus interface for any requests and redirects them to the appropriate applications.

In the sandbox, xdg-terminal-exec would be bundled (probably in the runtime) and would pass everything through to the TerminalExec portal. 

We don't want to use flatpak-spawn here at all. Unless bash scripts can interact with dbus like this too, it might be needed to rewrite it in another language.

**Comment by Mikilio** [comment]
I think this is an issue for [flatpak/xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal).

**Comment by orowith2os** [comment]
Yeah, plus I'm writing my own implementation of this tool in Rust anyways for the time being. Using it as a chance to learn more about serde and D-Bus.
