### ISSUE TITLE
Is this utility intended to wait for the command to exit?

### ISSUE THREAD

**Issue by smcv** [Vladimir-csp/xdg-terminal-exec#17]
Suppose we run a command that takes time, like this:

```
time xdg-terminal-exec sleep 10
```

There are two possible behaviours for this:

1. With a traditional, process-per-window terminal like `xterm -e`, x-t-e will end up running something like `xterm -e sleep 10`, which opens a window, runs `sleep 10`, waits for it to exit (in this case 10 seconds later), closes the window, and exits; so the `time` command will output 10 seconds + startup overhead.
2. With an IPC-based single-instance terminal like `gnome-terminal`, x-t-e will usually end up running something like `gnome-terminal -- sleep 10`, which sends IPC (often D-Bus) to the "factory" service asking for a window running `sleep 10`, waits for acknowledgement of the IPC command, and then exits. The output of the `time` command will be a fraction of a second, including the startup and IPC overhead but not the time taken to run the actual `sleep` command.

(Of course a more realistic command than `sleep 10` would be an interactive TUI like `mutt`, `irssi` or a shell.)

Some terminals default to (2.), but have a way to require the terminal to wait, like `gnome-terminal --wait`. If this option is used, the gnome-terminal client does not exit when the IPC command is acknowledged; instead, it waits for the "factory" service to report back "your command has finished", and *then* exits. This effectively changes their behaviour to (1.).

Other terminals default to (2.), but have a way to disable the use of IPC entirely and instead behave like `xterm`, like KDE's `konsole --nofork` (and historically `gnome-terminal --disable-factory`, but that option no longer exists). Again, this effectively changes their behaviour to (1.).

What is the intended behaviour of xdg-terminal-exec? Are terminals supporting this interface meant to behave like (1.) when launched via xdg-terminal-exec, or are they meant to behave like (2.) if possible, or is it unspecified (implementation-defined) whether we will see (1.) or (2.)?

If terminals supporting this interface are meant to aim for (1.), then I think they will need a way to tell `xdg-terminal-exec` what option or options are needed to enable that behaviour: for example this would be an empty list for xterm, or `--wait` for gnome-terminal. Or this could be done by replacing/augmenting `X-ExecArg` with something that can express more than one argument, so xterm would continue to use `-e` but gnome-terminal would use `--wait --` (or `--wait;--;` or however the file format might spell it).

Unfortunately, GNOME Console (kgx) has a `--wait` option, but [it's unimplemented and does nothing](https://gitlab.gnome.org/GNOME/console/-/issues/45), making it impossible for GNOME Console to implement (2.) without new code, as far as I can see.

**Comment by Vladimir-csp** [comment]
It is intended to work with whatever command the terminal's desktop entry has by `exec`-ing it. Since it uses it's own `xdg-terminals` heirarchy, such cases can be handled in specific desktop entry if possible (just add `--wait` in `Exec` for gnome-terminal). Any generic handling is out of scope, at least for now.

**Comment by Vladimir-csp** [comment]
Some tweaks to readme are required, at least.
