### ISSUE TITLE
will fail if command-line uses all ASCII punctuation

### ISSUE THREAD

**Issue by smcv** [Vladimir-csp/xdg-terminal-exec#18]
If the command to be executed includes all the ASCII punctuation characters, since resolving #12, the command will fail.

Is there a reason why it needs all this stuff with `\0`-delimited arguments? If I'm understanding correctly, the desired processing is:

* break up the `Exec` line as if via a shell, possibly including quoted spaces etc. in arguments;
* append the `X-ExecArg` if any, as a single argument;
* append `"$@"` as multiple arguments;
* exec the resulting `argv`

POSIX shells already have access to one array, `$@`, and it's possible to prepend and append with `set`; so I think the desired result can probably be achieved more easily by replacing everything from `# this variant is robust` to end-of-file with something like this:

```
# prepend EXECARG if any, for example -e for xterm, to $@
if [ -n "$EXECARG" ]; then
    set -- "$EXECARG" "$@"
fi
# prepend the terminal emulator itself to $@, word-splitting and unquoting $EXEC
eval "set -- $EXEC \"\$@\""
# run the terminal emulator
exec "$@"
```

Alternatively, an implementation in a programming language with fewer sharp edges, like Python, Perl or even C, wouldn't have to deal with all the weird shell-isms of a POSIX shell.

**Comment by Vladimir-csp** [comment]
Thanks! I rely on xargs for parsing a string with potentially complex and quoted args, and all the `\0` shenanigans spawn from here.
I looked at `set` for this task before, but missed `eval` as the final piece of the puzzle, since I'm just wary of it in general.
Will revisit this.

**Comment by smcv** [comment]
Looking at this again, I think there might be a separate bug in x-t-e's current handling of the `Exec` line (I'm just mentioning it here rather than opening an issue report since I haven't actually reproduced this). If the terminal emulator is something like

```
Exec=/usr/bin/my-terminal --comment="is the best"
X-ExecArg=-e
```

then I think `xdg-terminal-emulator mutt` would currently disregard the shell-style quoting rules in `Exec`, and instead just split it on whitespace, equivalent to this:

```
set -- \
    '/usr/bin/my-terminal' \
    '--comment="is' \
    'the' \
    'best"' \
    '-e' \
    'mutt'
```

But the correct argv would be more like this:

```
set -- \
    '/usr/bin/my-terminal' \
    '--comment=is the best' \
    '-e' \
    'mutt'
```

The .desktop file syntax is designed so that there are basically two ways you can parse `Exec`: you can either word-split it according to shell-style rules (like Python `shlex.split` and GLib `g_shell_parse_argv`), or you can pass it to a shell. GNOME and other GLib-based environments use the first approach, but I believe KDE uses the second. The specification makes sure that all the constructs that would be interpreted differently by those two approaches, like `$` variable references and `` ` `` command substitution, are not allowed (so they have [undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior), for which both the GNOME and KDE approaches are valid).

I think what I suggested in this issue would do the right thing for any `Exec` line that is allowed by the spec, assuming it doesn't have any `%x` field codes (which is why I'm using `eval`). It will do something weird if reserved characters like `$` or `` ` `` aren't quoted, but the .desktop spec intentionally says reserved characters must be quoted, so unquoted reserved characters have undefined behaviour anyway.

**Comment by smcv** [comment]
> I think [xdg-terminal-emulator] would currently disregard the shell-style quoting rules in Exec

... or maybe not, if you're using `xargs` to do that parsing - I'd missed that. (But then you've replaced the problem of parsing `Exec` with the problem of parsing `xargs` output, which is not *necessarily* any easier.)

**Comment by Vladimir-csp** [comment]
`xargs` serves exactly this purpose: to split complex arguments into `\0`-delimited string for further processing, so `Exec=/usr/bin/my-terminal --comment="is the best"` use case is supported.

**Comment by Vladimir-csp** [comment]
75fa03c9df3c96e16223f23b09f4d47e58a51233 seems to pass all the tests, but the issue with '$' in 'Exec=' remains for now.

**Comment by Vladimir-csp** [comment]
@fluvf maybe you have some ideas on how to not expand vars in `Exec=` while keeping complex args?

**Comment by fluvf** [comment]
Can you give me an example of a failing `Exec` key?
Giving it a quick look, `$` is a [reserved character](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables), and a naive
`echo 'a b \$c d' | sh -c 'read -r cmd; eval "set -- $cmd"; printf ">%s<\n" "$@"'`
just works

**Comment by Vladimir-csp** [comment]
Yes, escaped `\$` works. Well, let's write unescaped ones off to undefined behavior...

**Comment by fluvf** [comment]
I don't see any way to not expand any unescaped `$` and still undo quoting in the string
Maybe the "correct" behaviour in this case would be to expand any unescaped variables into null
Usually this would be done using `env -i`, but unfortunately `eval` can't be called that way
The script could try to control the environment, by either masking all known variables, or by doing a mass `unset` call
But that would quickly become unmaintainable, and would be special code handling a broken entry file
So I think leaving it at 'undefined behaviour' is the sane thing to do
