### ISSUE TITLE
Request: Use desktop files from standard locations

### ISSUE THREAD

**Issue by xiota** [Vladimir-csp/xdg-terminal-exec#28]
`.desktop` files are already located at standard locations, like `/usr/share/applications` and `$XDG_DATA_HOME/applications`.  Why aren't these pre-existing desktop files used instead of copying or linking to a new location?

**Comment by Vladimir-csp** [comment]
In theory, it is possible to filter stock entries by `TerminalEmulator` category, will consider this.

**Comment by Vladimir-csp** [comment]
Default behavior is not changed, please test with `use_stock_applications` line in config or `XTE_STOCK_TERMINALS=1` var.

**Comment by xiota** [comment]
Seems to work.  But I don't understand the purpose of the extra `xdg-terminals` folders.  For new users, creating them is an extra configuration step.  (And the new setting is another extra step.)  For users who already created the folders, switching to standard locations would most likely be transparent because that's where they most likely copied the files from.

**Comment by Vladimir-csp** [comment]
It was based on assumption that entries would have to be modified and separated from standard applications. In hindsight it seems that those concerns were overblown as filtering by `Categories` now seems pretty reliable (at least as I see it in Debian), and lots of terminals support `-e` as exec arg. Although there might still be potential performance issues with (at least with this particular implementation) due to lack of caching and the need to go through a ton of entries with one or more `grep` call.

This is just a proposal for a spec and a basic example of implementation. There were two XDG threads (subjects `Spec to define the default terminal?`,  `A spec to set default terminal applications?`) which since died out, and this proposal which had no movement as of now: https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3

If no negative feedback comes in, default behavior will change.

**Comment by xiota** [comment]
Thank you for explaining.  Makes sense.

**Comment by Vladimir-csp** [comment]
Unfortunately, "alternatives" and any other symlink-to-bin approaches do not mesh well with desktop entry/mime action stuff.

Well, the mechanisms are now in place, and even optimized.
If no further feedback comes in, say, this month, I'll switch default.

**Comment by xiota** [comment]
Minor issue.  Using `use_stock_applications`.  I installed and uninstalled an unrelated app.  It left behind an invalid desktop file in my home directory.  Then `xdg-terminal-exec` produced the following message:
```
/usr/bin/xdg-terminal-exec: line 151: alias: `userapp-xxxxxxxxxx-xxxxxx.desktop': invalid alias name
```

Deleting the file resolved the issue.

In a way this was good because it let me know there was a file to delete.  But could be confusing for some users.  Maybe invalid desktop files should be skipped?

**Comment by xiota** [comment]
Didn't look inside, and already deleted the problem file.  Since the app was already uninstalled, `exec` would point to non-existent path.

**Comment by Vladimir-csp** [comment]
non-existent `Exec` would invalidate and skip entry, here it seems there were something wrong with entry filename.

**Comment by xiota** [comment]
I just copied a good desktop file and changed the exec line to `Exec=testing-does-not-exist` and got the same error.  Using fc8a6e0.

**Comment by Vladimir-csp** [comment]
Please show `DEBUG=1 xdg-terminal-exec`

**Comment by xiota** [comment]
You're right.  Not related to `Exec`.  Happens with desktop files with space in name.  I was using file manager to copy the desktop file, and it names them `Original copy.desktop`.  Replacing space with dash resolves the issue.  Naming it something else with spaces, like `1 2 3.desktop` causes the issue to return.

**Comment by Vladimir-csp** [comment]
Unfortunately it is hard to do a proper regexp check on desktop entry name validity when limited to POSIX `sh` and `find`.

**Comment by Vladimir-csp** [comment]
...but not impossible 2f48abc

**Comment by xiota** [comment]
Successfully launches the terminal, but displays error.  Using 2f48abc.

```
failed to register '.../.local/share/applications/1 2 3.desktop' as entry '1 2 3.desktop'
```

**Comment by Vladimir-csp** [comment]
Yes, this is intended behavior, as desktop entry name is not [valid](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html#desktop-file-id)

**Comment by xiota** [comment]
It's *not* invalid.  That part of the specification says *should* not *must.  That means implementers are recommended to follow it, but are *not* required to.  It's fine if this is intended, but would probably be better to make a more informative "info" message (eg, "unsupported...") than something that looks like an error ("failed...").

**Comment by Vladimir-csp** [comment]
Well, it is done, 3fa224f9d2241e6f1788f7346e8ce2ecdbee8d31. No need to wait what's left of this day.
