### ISSUE TITLE
line 151: alias: =entry_path='': not found

### ISSUE THREAD

**Issue by uetcis** [Vladimir-csp/xdg-terminal-exec#34]
The following error is generated when running `xdg-terminal-exec`:

```
/usr/bin/xdg-terminal-exec: line 151: alias: =entry_path='': not found
```

**Comment by Vladimir-csp** [comment]
What does `DEBUG=1 xdg-terminal-exec` show?

**Comment by uetcis** [comment]
> What does `DEBUG=1 xdg-terminal-exec` show?

```
lowercase desktops are: 'hyprland'
reading config '/home/weitcis/.config/hyprland-xdg-terminals.list'
reading config '/home/weitcis/.config/xdg-terminals.list'
reading config '/etc/xdg/hyprland-xdg-terminals.list'
reading config '/etc/xdg/xdg-terminals.list'
searching for terminal entries in 'xdg-terminals'
searching '/home/weitcis/.local/share/xdg-terminals/'
searching '/usr/local/share/xdg-terminals/'
searching '/usr/share/xdg-terminals/'
found desktop entry ''
adding fallback ID ''
/bin/xdg-terminal-exec: line 151: alias: =entry_path='': not found
```

**Comment by Vladimir-csp** [comment]
You do not have any terminal entries in `xdg-terminals` subdirs, but I can not reproduce this particular shell failure on dash.
Please show `ls -l /bin/sh`
Check what happens with fc8a6e0a4, should be a proper error `No valid terminal entry was found in xdg-terminal`.

**Comment by uetcis** [comment]
> You do not have any terminal entries in `xdg-terminals` subdirs, but I can not reproduce this particular shell failure on dash. Please show `ls -l /bin/sh` Check what happens with [fc8a6e0](https://github.com/Vladimir-csp/xdg-terminal-exec/commit/fc8a6e0a45f8b19874a7cb44ed0b6985d9721a23), should be a proper error `No valid terminal entry was found in xdg-terminals`.

```
$ DEBUG=1 /bin/xdg-terminal-exec
lowercase desktops are: 'hyprland'
reading config '/home/weitcis/.config/hyprland-xdg-terminals.list'
reading config '/home/weitcis/.config/xdg-terminals.list'
reading config '/etc/xdg/hyprland-xdg-terminals.list'
reading config '/etc/xdg/xdg-terminals.list'
searching for terminal entries in 'xdg-terminals'
searching '/home/weitcis/.local/share/xdg-terminals/'
searching '/usr/local/share/xdg-terminals/'
searching '/usr/share/xdg-terminals/'
empty data: entry_path: "", entry_id: ""
final entry ID list ''
No valid terminal entry was found in xdg-terminals

$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Oct  8 00:27 /bin/sh -> bash*

$ pacman -Q bash
bash 5.2.015-5
```

**Comment by Vladimir-csp** [comment]
OK, cool.
To get it working, either copy some terminal entries to one of `xdg-terminals` subdirs, or add `use_stock_applications` line to `xdg-terminals.list` (more future-proof, would like to have some feedback on speed), or wait till December when I change the default behavior to use stock entries :).

**Comment by uetcis** [comment]
It works now, thanks a lot :)
