### ISSUE TITLE
Somewhere between rofi, xdg-terminal-exec, and xdg-terminal something happens

### ISSUE THREAD

**Issue by mcepl** [Vladimir-csp/xdg-terminal-exec#35]
(I am sorry for abusing this issue tracker for something which is most likely a support question, but I haven’t found a better channel for communication)

I am trying to make `Terminal=true` applications to run on [Moldavite](https://sr.ht/~mcepl/moldavite/) (MicroOS and Sway-based distro) using `xdg-terminal-exec` for it. Using the latest openSUSE package of it (`20231124+git.fc8a6e0`) I got stuck somewhere in the middle and I don’t know how to move ahead.

On the host system terminal (i.e., outside of any podman containers) when I run either of these commands they work correctly and new window with running applications is opened:

```sh
# referring to ~/.bin/gomuks script and
# (I assume) ~/.local/share/xdg-terminals/org.codeberg.dnkl.foot.desktop
$ xdg-terminal gomuks
# referring to ~/.local/share/applications/gomuks.desktop which calls `gomuks` command
$ xdg-terminal-exec gomuks
# Select the application from the menu
$ rofi -show combi -modes combi -combi-modes "drun,run"
```

However, when I run the last command directly from Sway (not from the foot/bash session) I get not response at all, and I find in the system log line:

```
Nov 25 21:29:59 mitmanek.cepl.eu sway[7905]: xdg-terminal: configured terminal program 'xterm' not found or not executable
```

Does `xdg-terminal-exec` depend on some environment variable, which is not set in outside of the terminal session?

`~/.config/xdg-terminals.list` contains:

```
org.codeberg.dnkl.foot.desktop
org.gnome.Terminal.desktop
```

and there is `org.codeberg.dnkl.foot.desktop` both in `~/.local/share/xdg-terminals/` and in `/usr/share/xdg-terminals`.

**Comment by Vladimir-csp** [comment]
I do not recognize this error message. Is `xdg-terminal` the same tool, or some other implementation?

**Comment by mcepl** [comment]
On Sat Nov 25, 2023 at 11:08 PM CET, Vladimir-csp wrote:
> I do not recognize this error message. Is `xdg-terminal` the
> same tool, or some other implementation?

It is from xdg-utils (xdg-utils-1.2.0~beta1+20230929).

**Comment by Vladimir-csp** [comment]
It seems to have no relation to this proposed spec, instead it tries to guess current desktop environment mechanism and use it, otherwise falling back to `terminal_generic` function which eventually falls back to `xterm`.
