### ISSUE TITLE
Consider moving to gitlab.freedesktop.org

### ISSUE THREAD

**Issue by emersion** [Vladimir-csp/xdg-terminal-exec#37]
Other FreeDesktop projects are hosted there. It's not proprietary like GitHub.

**Comment by Vladimir-csp** [comment]
Thanks, I'm considering at least making mirrors. My two flagship projects would fit there nicely.

**Comment by Vladimir-csp** [comment]
No pull mirroring available?

**Comment by emersion** [comment]
Nope, I don't believe so.

**Comment by Vladimir-csp** [comment]
ok, will live with that... )

**Comment by arrowd** [comment]
If the canonical location of this project is the FDO GitLab instance then this project shouldn't allow creating issues and PRs.

**Comment by waldyrious** [comment]
For reference, here's the link to the GitLab repo: https://gitlab.freedesktop.org/Vladimir-csp/xdg-terminal-exec/
