### ISSUE TITLE
xdg-terminal-exec cuts arguments from Exec line

### ISSUE THREAD

**Issue by FreeSlave** [Vladimir-csp/xdg-terminal-exec#4]
It should not. Exec value has a right to have arguments. E.g. if I want to start terminal with certain options.

**Comment by Vladimir-csp** [comment]
I probably misinterpreted some parts of xdg-open. Fixed in 9e4fcb3.
Do you think it would still need some filter to remove '%' fields? I doubt that any terminal would use them, but still.

**Comment by FreeSlave** [comment]
They may use %k and %c.
I don't know if it's important to implement support for fields. Personally I see xdg-terminal-exec shell script as more like example of proposed spec implementation, not something that could be used in wild. I would prefer native app instead of shell script here. Desktop Entries is not easy thing even in compiled languages because of all these unquoting/unescaping rules.
Anyway, I'm closing issue since it's fixed. Just remember to run ./test/runtests.sh if you change something. I know my test-suite is far from being perfect, but still better than nothing.
