### ISSUE TITLE
Cache can end up being used even when disabled in `*xdg-terminals.list`

### ISSUE THREAD

**Issue by fluvf** [Vladimir-csp/xdg-terminal-exec#47]
xdg-terminals.list:
```
/disable_cache
```
Steps to reproduce:
```
$ env XTE_CACHE_ENABLED=1 ./xdg-terminal-exec
# cache used as requested
$ ./xdg-terminal-exec
# cache used while still being explicitly disabled
```
I can't see any easy solutions
As for hard ones:
1. Always read `*xdg-terminals.list` files
2. Remove directives
3. Don't support `$XTE_CACHE_ENABLED`
4. Something else?

I'm not a fan of 3.

**Comment by Vladimir-csp** [comment]
4. document this behavior
5. something like this forked in parallel with normal cache read:
```
{
	check_bool "${XTE_CACHE_ENABLED-}" && exit 0
	read_config_paths
	check_bool "$CACHE_ENABLED" && exit 0
	save_cache
} &
```
It will see `/disable_cache` in config and remove the cache, at a cost of one wrongfully cached run.

**Comment by fluvf** [comment]
If you're happy with 4. then that seems like the way to go
5. feels like a hack and could result in some (unlikely) bugs with directories / files changing at a wrong time
