### ISSUE TITLE
xdg-terminal-exec misbehaves if TERMINAL env var is set

### ISSUE THREAD

**Issue by uninsane** [Vladimir-csp/xdg-terminal-exec#50]
- i export TERMINAL=alacritty in ~/.profile for applications which read that env var.
- with this variable set, `xdg-terminal-exec` launches libreoffice (`xsltfilter.desktop`) -- not expected, it's not even a terminal!
- with `env -u TERMINAL xdg-terminal-exec`, alacritty is launched (`Alacritty.desktop`) -- the expected behavior.

i notice xdg-terminal-exec is using `TERMINAL` as its own variable internally: specifically, i expect this line may be causing it to incorrectly believe that certain .desktop files represent a terminal?
```sh
# ensure entry is a Terminal Emulator
[ -z "${TERMINAL-}" ] && continue
```

Alacritty.desktop:
<details>
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=alacritty
Icon=Alacritty
Terminal=false
Categories=System;TerminalEmulator;

Name=Alacritty
GenericName=Terminal
Comment=A fast, cross-platform, OpenGL terminal emulator
StartupNotify=true
StartupWMClass=Alacritty
Actions=New;

[Desktop Action New]
Name=New Terminal
Exec=alacritty
</details>

xsltfilter.desktop:
<details>
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Exec=soffice %U
MimeType=application/vnd.oasis.opendocument.text-flat-xml;application/vnd.oasis.opendocument.spreadsheet-flat-xml;application/vnd.oasis.opendocument.graphics-flat-xml;application/vnd.oasis.opendocument.presentation-flat-xml;
Name=LibreOffice 7.6 XSLT based filters
GenericName=XSLT based filters
GenericName[ar]=مرشّحات تعتمد XSLT
GenericName[ca]=Filtres basats en XLST
GenericName[cs]=Filtry používající XSLT
GenericName[da]=XSLT baserede filtre
GenericName[de]=XSLT basierte Filter
GenericName[en]=XSLT based filters
GenericName[en_GB]=XSLT based filters
GenericName[eo]=XSLT-bazitaj filtriloj
GenericName[es]=Filtros basados en XSLT
GenericName[fi]=XSLT-pohjaiset suodattimet
GenericName[fr]=Filtres basés sur XSLT
GenericName[hu]=XSLT-alapú szűrők
GenericName[it]=Filtri basati su XSLT
GenericName[ja]=XSLTベースのフィルター
GenericName[nl]=Filters gebaseerd op XSLT
GenericName[pl]=Fltry bazujące na XSLT
GenericName[pt]=Filtros baseados em XSLT
GenericName[pt_BR]=Filtros baseados em XSLT
GenericName[ro]=Filtru bazat pe XSLT
GenericName[ru]=Фильтры XSLT
GenericName[sl]=Filtri na osnovi XSLT
GenericName[tr]=XSLT tabanlı süzgeçler
GenericName[uk]=Фільтри XSLT
GenericName[zh_CN]=基于 XSLT 的过滤器
NoDisplay=true
StartupNotify=true
X-GIO-NoFuse=true
X-KDE-Protocols=file,http,ftp,webdav,webdavs
</details>

log for `env TERMINAL=alacritty DEBUG=1 xdg-terminal-exec`:
- [xdg-terminal-exec-bad.log](https://github.com/Vladimir-csp/xdg-terminal-exec/files/14730938/xdg-terminal-exec-bad.log)

log for `env -u TERMINAL DEBUG=1 xdg-terminal-exec`:
- [xdg-terminal-exec-good.log](https://github.com/Vladimir-csp/xdg-terminal-exec/files/14730940/xdg-terminal-exec-good.log)

system info:
- xdg-terminal-exec 0.9.0
- OS: nixos
- desktop: sway

**Comment by Vladimir-csp** [comment]
Thanks!
