### ISSUE TITLE
Ignores entries with `Hidden=false`

### ISSUE THREAD

**Issue by dcompoze** [Vladimir-csp/xdg-terminal-exec#51]
When the terminal emulator `.desktop` file has a field `Hidden=true` it's ignored by `xdg-terminal-exec` (correctly I would assume).

But when the field is set to `Hidden=false` it's also ignored by `xdg-terminal-exec`, which I would expect to be unintentional.

Only removing the `Hidden` field altogether makes the `.desktop` entry work correctly.

**Comment by Vladimir-csp** [comment]
Thanks for catching this!
