### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by quantenzitrone** [Vladimir-csp/xdg-terminal-exec#52]
I'm kinda confused...

What is the spec called:
- XDG Terminal Execution Spec
- Default Terminal Execution Spec
- Default Terminal Spec

What is the utility called:
- XDG Terminal Execution Utility
- Default Terminal Execution Utility

My understanding is that the Utilty is a program that implements the spec, while this repository provides a shell-based reference implementation for that.

I was trying to review a pr (https://github.com/NixOS/nixpkgs/pull/303225) adding a module for that to NixOS and I thought about this way too much.

Also why is the spec not a separate document and have there been attempts to add the spec to freedesktop.org?

**Comment by Vladimir-csp** [comment]
Hi!
https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3 in progress since 2019 ) Being improved along the way. You may find the spec as a separate document there.

Yes, the terminology might need some cleanup, thanks for bringing this up!

**Comment by Vladimir-csp** [comment]
What do you think?

**Comment by quantenzitrone** [comment]
Thanks, I think thats better.
The repository description (the short text in the upper right corner on GitHub) still probably needs an edit.
